Repository developmentseed/scoreboard, pull requests merged in 2020-04, with the labels that each got.

#530 Add OSM-teams statistics page
  .gitignore
  api/bin/README.md
  api/src/routes/teams.js
  api/src/utils/osmesaStatus.js
  components/common/Table.js
  components/teams/TeamBlurb.js
  lib/i18n/glossary_en.json
  lib/utils/format.js
  package.json
  pages/team.js
  pages/teams.js
  styles/core/_base.scss
  styles/core/_layout.scss
  styles/pages/_campaigns.scss
  yarn.lock
Labels: enhancement

#552 Fix Next.js deprecation warning; Fix IDE warning.
  components/dashboard/DashboardBlurb.js
Labels: bug

#553 Dashboard improvements and fixes.
  components/AssignmentsTable.js
  components/dashboard/DashboardAssignments.js
Labels: bug

#555 Fix React warning
  components/charts/CampaignsChart.js
Labels: bug

#547 Team Stats page: empty state, edge cases
  api/src/routes/teams.js
  api/src/services/teams.js
  components/teams/TeamBlurb.js
  lib/utils/teams.js
  pages/team.js
Labels: enhancement

#518 Feature/edit team
  api/src/routes/teams.js
  components/teams/LocationInput.js
  components/teams/TeamCampaignsForm.js
  components/teams/TeamDetailsForm.js
  components/teams/TeamMembersForm.js
  lib/i18n/glossary_en.json
  lib/store/actions/teams.js
  package.json
  pages/_app.js
  pages/create-team.js
  pages/edit-team-details.js
  server.js
  styles/components/_forms.scss
  tests/containers.test.js
  yarn.lock
Labels: Teams Integration, enhancement

#562 Teams index page: Add public teams and filters for user's teams
  pages/teams.js
Labels: enhancement
